### ISSUE TITLE
[DNS] Dune developer preview url

### ISSUE THREAD

**Issue by maiste** [ocaml/infrastructure#156] opened 2024-09-23 10:14 UTC
Hi :wave: 
We are on our way to publish the Dune Developer Preview to the public (with Dune package management as a notorious feature). Currently, the website is host under https://dune.ci.dev and https://download.dune.ci.dev (and developed at https://github.com/tarides/dune-binary-distribution). However, as it will be on the https://ocaml.org website (Draft PR: https://github.com/ocaml/ocaml.org/pull/2706), we would like to add a new subdomain for this under the ocaml.org domain. 

Our suggestion would be to have:
- `dune.ocaml.org` to replace `dune.ci.dev`
- `get.ocaml.org` to replace `download.dune.ci.dev`

The DNS would be the following:
```dns
dune.ocaml.org CNAME tarides.github.io.
get.ocaml.org A 51.159.152.205
get.ocaml.org AAAA 2001:bc8:1202:dc31::1
```

The CNAME is temporary, as we host the website on GitHub for the development period.

**Comment by avsm** [comment] 2024-09-26 11:24
I've asked @mtelvers to look into this. We generally don't point ocaml.org URLs at external infrastructure if we can avoid it, so he'll help figure out how to make this reproducible.

**Comment by maiste** [comment] 2024-09-26 12:01
Sure! `get.ocaml.org` point to Scaleway machine from the current infrastructure, if I'm not mistaken. For `dune.ocaml.org`, I will check with @shonfeder and @mtelvers if we can store it in a machine inside the infrastructure. This is just a static website from a git repository :+1:

**Comment by dra27** [comment] 2024-09-26 13:46
Just as a reference point: although there's not a timeline, the long-term trajectory for opam.ocaml.org is to retire it (by merging what's left of it into the main website) - its separation from the main ocaml.org is mostly a historical necessity which has remained. It is also built and deployed by the [deploy.ci.ocaml.org](https://deploy.ci.ocaml.org/?repo=ocaml-opam/opam2web&).

**Comment by dra27** [comment] 2024-09-26 13:49
Two general points:
- Separately from whether get.ocaml.org is a good idea or not in the long-term, it seems wholly inappropriate at this time when Dune DP supports less than https://ocaml.org/docs/installing-ocaml
- Looking very briefly at the repos backing them, is data collection on both sites compatible with https://ocaml.org/policies/privacy-policy?

**Comment by maiste** [comment] 2024-09-26 14:29
In the future (hopefully soon), the content from https://dune.ocaml.org (currently dune.ci.dev) would move to https://ocaml.org under the installation section. As long as it is still in testing mode, it is important to have a clear separation (a different subdomain). Note here that `get.ocaml.org` is not a website, but a URL pointing to the dune binaries.

To address your two points:
- The idea is to mirror what is done by other distributions (for example [cargo](https://doc.rust-lang.org/cargo/getting-started/installation.html)). I can't get that it is misleading the user. Would `sh.ocaml.org` be better? There is not this idea of "getting OCaml" and it's a short URL we could use :thinking: 
- The first one is just a caddy web server, serving binaries, so there is no data collection. https://dune.ocaml.org (currently dune.ci.dev) is using the same technology to count visit than OCaml.org: plausible. It's GDPR friendly and respect privacy :lock:

**Comment by dra27** [comment] 2024-09-26 14:48
So, for example, while clear separation is needed, what's wrong with putting something on https://dune.build?

"Get OCaml" / "Install OCaml" - same thing (and the latter is the title of an ocaml.org)

For the comparison with Rust to be valid, we'd be talking about the link being get.rust-lang.org or sh.rust-lang.org - but it's sh.rustup.rs. Again, what would be wrong with https://sh.dune.build in the meantime?

**Comment by maiste** [comment] 2024-09-26 15:20
I understand the comparison but if I would be nitpicky I would say that opam shouldn't live on `opam.ocaml.org` but on `opam.org` following your reasoning :thinking: It would be the same as having `dune.ocaml.org`, no? If I understand the issue with the `get.ocaml.org` and the `sh.ocaml.org` (not make it the default endpoint until Dune as a package manager is mature), I don't see why having `dune.ocaml.org` would be an issue...

About the `dune.build`, FMU, we don't have "direct" control over the domain.

**Comment by dra27** [comment] 2024-09-27 08:16
I'm sure not which nit you're picking! 😊 I'd already said:

> the long-term trajectory for opam.ocaml.org is to retire it (by merging what's left of it into the main website)

There is a slight apples-vs-oranges comparison in that opam.ocaml.org also serves the http remote opam-repository, which _is_ the official package repository, so there's likely to be https://opam.ocaml.org/index.tar.gz for a looong time, but the if the long-term goal is that https://opam.ocaml.org redirects into the main website, that seems a pretty concrete reason _not_ to add any others (dune.ocaml.org included) in the meantime.

Anyway, we digress.

https://dune.build is serving https://github.com/ocaml/dune-www which from here seems a far better temporary home for the page (while content on ocaml.org is being prepared/updated) than dune.ocaml.org. I can grant you access to that, but so too can other Dune maintainers, cc @snowleopard; @rgrinberg (I'm aware @​emillon is away at the moment).

For the DNS, has actual control of dune.build been lost? I'm not sure whether @avsm holds the registration, Jane Street, or Jérémie Dimino. Even if it has, is get.dune.build so superior to dune.build/get (it may be)?

**Comment by mtelvers** [comment] 2024-09-27 08:30
We should also move https://github.com/tarides/dune-binary-distribution to https://github.com/ocaml-dune.

**Comment by maiste** [comment] 2024-09-27 08:59
Haha, fair enough :laughing: 
I was just trying to point the fact that https://opam.ocaml.org is the same as having https://cargo.rust-lang.org (which is not the case). And indeed, if the objective is to retire https://opam.ocaml.org my remark doesn't make sense. I agree this is a strong digression on the initial subject haha

About the original subject, my point was poorly express then. I try it in another way. Why is it a problem to have opam.ocaml.org or add another subdomain? The idea of having it under the *.ocaml.org subdomain is to make dune official. Even if this is a preview, and it will take time to get more functionalities, it's important that people understand this is an official project. Staying on the ocaml.org domain provides this. However, if we can make https://dune.build as official from the ocaml.org perspective (link, pointers, etc), I'm fine with this idea :smile: 

However, in terms of control, we need to make sure that the entire Dune team have control over. Otherwise, it would be hard to do some changes here. Maybe moving the ownership to the infrastructure team could help, I don't know.

About the URL, it would be OK for the website to have a sub path in https://dune.build/preview (even if preview.dune.build is shinier haha) but we also need to have a specific subdomain to point to the binaries as they are served from another server.

And for the organisation, as far as I'm aware, we are not part of the team of `ocaml-dune`. As a result, if we would be maintainer in `ocaml-dune` and have control in some way over the https://dune.build DNS, I would be happy to do so. Unfortunately, this is not the case.

Also, I'm not the one with the decision power here. If I were definitely OK (under the with control condition) to have it under the dune hat, I don't make the last call.

**Comment by mtelvers** [comment] 2024-09-27 09:53
@gridbugs, among others, is a maintainer of the `ocaml-dune` organisation.

**Comment by avsm** [comment] 2024-09-27 11:52
I originally bought dune.build with Jeremie Dimino when we started Dune, and am entirely happy to redirect anything under there as requested, and can delegate DNS access to @mtelvers.  I entirely agree with @dra27 that it's more appropriate to bring things under the ocaml.org banner once they are less experimental.

The reason that opam.ocaml.org exists is that it is indeed a highly stable and supported service for the opam-repository that I would jump out of bed at 3am to fix if it's down. I do not plan to jump out of bed at 3am to fix a dune package management outage while it's experimental -- but I won't need to, since it uses the opam repository hosted at opam.ocaml.org to my understanding! :-)

**Comment by leostera** [comment] 2024-09-27 12:48
Thanks for the inputs folks. We'll use the dune.build subdomains for now.

**Comment by avsm** [comment] 2024-09-28 15:44
Sounds like we have consensus on using dune.build for now, thanks! @mtelvers has access to that domain now, so I'll close this.

**Closed by avsm** 2024-09-28 15:44 UTC
