### ISSUE TITLE
Staging environment for OCaml.org's documentation pipeline

### ISSUE THREAD

**Issue by tmattio** [ocaml/infrastructure#18] opened 2022-11-07 11:07 UTC
In the context of improving OCaml.org's documentation pipeline, we'd like to apply changes to odoc, voodoos, and other projects that the pipeline uses to generate the documentation.

We test these changes locally, however, it'd be best to test them on a production-like environment before they are pushed in production.

The docs pipeline, which outputs its result to https://docs-data.ocaml.org/live/ currently listens to changes on the `main` branch of https://github.com/ocurrent/ocaml-docs-ci. We propose to have a staging environment for that pipeline that will listen to the `staging` branch of that repository and will output its result to https://docs-data-staging.ocaml.org/live/.

OCaml.org's own staging environment can then be updated to set the `OCAMLORG_DOC_URL` environment variable to `https://docs-data-staging.ocaml.org/live/` so changes to the docs pipeline staging environment can be tested visually on https://staging.ocaml.org/.

**Comment by avsm** [comment] 2022-12-15 12:30
Sounds fine to me. Do you need additional machines provisioned for this @mtelvers? It looks like it should be fine with existing servers and the build cluster.

**Comment by mtelvers** [comment] 2022-12-15 16:45
Yes, please.  We can delete `ci6` (Scaleway IP 51.15.222.237), which we have previously confirmed as spare and provision a new machine for this staging environment.  We would need a reasonable amount of CPU/RAM for the solver step plus ~250GB for the data.  The live implementation on `eumache` uses 650GB, but it appears to have several versions of the data.  Please can you point `staging.docs-data.ocaml.org` and `staging.docs-ci.ocaml.org` to the new machine?  These DNS names follow the pattern of `staging` being the prefix, such as for `staging.opam.ocaml.org`

**Comment by sabine** [comment] 2022-12-16 13:24
@avsm @mtelvers Thank you, this will be very helpful when we do major cleanups, fixes and improvements on the pipeline in 2023. Being able to keep the old version of the pipeline running while the new pipeline version does a full rebuild of the package documentation allows us to deploy safely and without downtime. I expect the deployment process to go like this:
1) apply a patch to `staging.docs-ci.ocaml.org` and wait for all packages to build
2) test the corresponding ocaml.org patch on staging.ocaml.org with data from `staging.docs-data.ocaml.org` to confirm that everything works end-to-end
3) apply patch to ocaml.org and point it to `staging.docs-data.ocaml.org`
4) wait a few days to confirm that there was no unexpected fatal slip-up that warrants a quick revert
5) update `docs-ci.ocaml.org` and wait for all packages to build
6) make ocaml.org use the regular `docs-data.ocaml.org` again. 

Since this is Scaleway, do you think we can put the staging pipeline to sleep when we are not actively using it? Technically, it does not need to run all the time.

**Comment by TheLortex** [comment] 2023-01-02 13:43
Note that its possible to use the `--limit <n>` and `--filter <pkgs>` command line options in docs CI to instanciate the CI with a reduced set of packages and number of versions, so that the deployment is not too costly. 

In that situation the deployment of a staging CI would be very useful to test experimental changes.

**Comment by avsm** [comment] 2023-01-03 20:23
I just wanted to check how long we would need this staging VM for with the large amount of memory for the solver.  It's a lot of resources to dedicate to something that is only used for staging, and ideally we would use a shared service for this.

For example, is there a solver service going live that would reduce the memory requirements? Disk space isn't too much of a concern, but memory is a fairly scarce and energy hungry resource.

Provisioning a larger machine in the short term isn't a problem if it unblocks development of course! I just don't want lots of resources sitting idle for a long time.

**Comment by TheLortex** [comment] 2023-01-16 13:03
> how long we would need this staging VM for with the large amount of memory for the solver. It's a lot of resources to dedicate to something that is only used for staging, and ideally we would use a shared service for this.

The staging VM doesn't need to be powerful. We can configure the CI to track a small set of packages.

**Comment by avsm** [comment] 2023-01-21 12:00
Thanks @TheLortex; @mtelvers could you please give me an indication of what sort of VM you need for this with that in mind? Smaller than [indicated here](https://github.com/ocaml/infrastructure/issues/18#issuecomment-1353381167) from the sounds of it.

**Comment by avsm** [comment] 2023-02-28 14:12
Is this still necessary, and if so, could you please let me know the VM resources needed please? /cc @sabine @tmattio.

**Comment by sabine** [comment] 2023-02-28 14:32
At this time, I think it's up to @tmcgilchrist to make a decision on that.

**Comment by tmcgilchrist** [comment] 2023-02-28 22:45
Hi @avsm, Could we get a smaller machine? Maybe PRO2-M or GP1-M (16 CPU, 64GB RAM and 200Gb+ storage) looking at the Scaleway instances available. We can look at trimming the number of versions / packages as @theLortex suggested above.

Eventually we want to move the solving off this machine and offer it as a service from the cluster. But we are not ready to do that yet. Once we can use the solver service both production and staging machines can be downsized considerably.

**Comment by avsm** [comment] 2023-03-05 17:51
@mtelvers I've set up docs-staging.sw.ocaml.org for this purpose.  However, might you please also make a note in the machine table that this needs to be revisited in six months or so?  It's a pretty big machine to dedicate to just staging, but obviously just fine for migratory purposes until the solver service can come live.

@tmcgilchrist might you be able to create a page/issue here somewhere about the solver service, and its status/scope?  It sounds like a generally useful piece of infrastructure to provide to other projects that might also need to solve-as-a-service.  But in the short term, I primarily just want to ensure we don't forget to decommission this big VM to keep our energy usage down.

**Comment by mtelvers** [comment] 2023-03-07 14:46
@avsm Thank you.  I have setup the docs staging environment at https://docs-staging.sw.ocaml.org

@tmattio @sabine Please can you confirm that you are happy for me to close down the temporary environment at https://docs.ocamllabs.io

**Comment by tmcgilchrist** [comment] 2023-03-07 21:47
@avsm the solver service is available at https://github.com/ocurrent/solver-service and is accessible via capnp. It is under heavy development so the docs haven't stabilised yet. 

The plan is to use it distribute solver jobs from [ocaml-ci](https://github.com/ocurrent/ocaml-ci) and [ocaml-multicore-ci](https://github.com/ocurrent/ocaml-multicore-ci) onto the cluster. This will let us free up hardware for running those services and use a shared ARM64 worker to run solves.  Once we have those deployed and stabilised, we can look at distributing the [docs-ci](https://github.com/ocurrent/ocaml-docs-ci) solves to the cluster. In the future there are other solver workloads we could distribute in this way.

**Comment by tmattio** [comment] 2023-03-09 23:43
> @tmattio @sabine Please can you confirm that you are happy for me to close down the temporary environment at https://docs.ocamllabs.io/

I'm not completely up to speed on the status of the work that needed that temporary env. I think that should be ok, but I'll defer to @sabine.

**Comment by sabine** [comment] 2023-03-10 06:03
Yes, closing down the temporary environment is fine!

**Comment by tmcgilchrist** [comment] 2023-03-14 08:55
@avsm Can you confirm the https://docs.ocamllabs.io/ env is shutdown? Then we can close this issue off.

**Comment by mtelvers** [comment] 2023-03-14 09:57
@tmcgilchrist The temporary VM running docs.ocamllabs.io has been destroyed.

**Closed by mtelvers** 2023-03-14 09:57 UTC

**Comment by tmcgilchrist** [comment] 2023-03-16 04:03
Thanks @mtelvers
